stages:
  - build

variables:
  FLUTTER_VERSION: "3.3.2"

before_script:
  - apt-get update
  - apt-get install -y curl unzip xz-utils zip libglu1-mesa
  - curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz
  - tar xf flutter_linux_${FLUTTER_VERSION}-stable.tar.xz
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor

build:
  stage: build
  script:
    - flutter pub get
    - flutter pub run build_runner build
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk